### ISSUE TITLE
Could you please tell me how to assemble the servo motor and rotary encoder?

### ISSUE THREAD

**Issue by Suptree** [verlab/hero_common#13]
Thank you for your response the other day.
Thanks to your help, I was able to attach all the electronic components to the PCB board by soldering.
And I am currently working on the assembly as described in the wiki.

So, two questions have come up.
One, do I need parts to connect the rotary encoder and encoder_shaft (3d parts)? I am thinking it is like a stick that goes through each other's holes.

Two, I can't get the servo motor and motor_gear(3d parts) to connect properly.

I am looking at the cad model to assemble it, but I couldn't figure it out.

I am sorry for your time, but I would appreciate it if you could help me.

![IMG_3679](https://user-images.githubusercontent.com/50046904/194711005-dfa856e5-609d-42a0-97c2-f0f9e7ec3d01.jpeg)
![IMG_3680](https://user-images.githubusercontent.com/50046904/194711008-2ac511d5-2a0b-4f92-8330-ca525436c84e.jpeg)
![IMG_3681](https://user-images.githubusercontent.com/50046904/194711009-a3f0e651-96dc-4c85-80b0-cf80982b385f.jpeg)
![IMG_3682](https://user-images.githubusercontent.com/50046904/194711010-76461e37-7a88-47c3-890f-cb6983d272f4.jpeg)
![IMG_3683](https://user-images.githubusercontent.com/50046904/194711011-a68c7829-80be-4ce8-949d-6855504ec0c8.jpeg)
![IMG_3684](https://user-images.githubusercontent.com/50046904/194711012-b55f136f-5518-46a2-b5e4-da9461d38721.jpeg)
![IMG_3685](https://user-images.githubusercontent.com/50046904/194711013-9ded9cad-79cf-4026-ade6-2c1ac94606d3.jpeg)

**Comment by rezeck** [comment]
Hi @Suptree,

It's nice to hear about your progress in developing the robot.

I still could find time to update the assembly tutorial, but these days I managed to create a step-by-step guide for this issue. I will update the [site](https://verlab.github.io/hero_common/assembly/#Wheel-Assembly) soon.

The following steps should help you with these two points. Please, let me know if it works for you.

1) A shaft for the rotary encoder + pinion gear
2) A way to couple the motor gear onto the servo shaft.

Steps:
1) A shaft for the rotary encoder + pinion gear
a) Remove the shank:
![image](https://user-images.githubusercontent.com/14208261/194779418-8a7c81ce-2db2-445e-b015-d2dc2b1d2229.png)
![image](https://user-images.githubusercontent.com/14208261/194779423-dec72f83-2f8e-4f72-9414-b2e6ba79212d.png)

b) Mandrel diameter should be around 1.80mm to fit into the encoder.
![image](https://user-images.githubusercontent.com/14208261/194779433-e572119d-7f09-4b67-9be0-8a0c27504d57.png)
![image](https://user-images.githubusercontent.com/14208261/194779436-38a0a4a1-49af-470a-9717-349497218f89.png)

c) Cut the dented part with pliers, leaving only the smooth part of the mandrel. 
![image](https://user-images.githubusercontent.com/14208261/194779441-e3003b55-c56c-4a28-be82-830cbe6667b9.png)

d) Cut the rest in half. We are going to build two encoder shafts.
![image](https://user-images.githubusercontent.com/14208261/194779444-cff31d1a-84e1-4e10-ba53-d858c0772543.png)

e) Remove imperfections from the cut. The base should be as flat as possible.
![image](https://user-images.githubusercontent.com/14208261/194779450-2f502aac-9ac9-4fee-9822-ddcb13353ee2.png)

f) Use a hammer to insert the shaft into the pinion gear.
![image](https://user-images.githubusercontent.com/14208261/194779453-eb194be3-db43-4b19-aa37-58e970cd47c1.png)

g) Make the shaft at least 9mm.
![image](https://user-images.githubusercontent.com/14208261/194779459-eb0c4e93-38e8-45c3-84bd-9dccc1445d6b.png)

h) Remove artifacts in the pinion gear and make it as clean as possible.
![image](https://user-images.githubusercontent.com/14208261/194779463-cd8246f0-128d-4cf8-97ed-4b7ac173f371.png)

i) Usually, encoders have a metal clip that gives the feeling of wheel steps on the mouse. Use a spatula to knead and flatten this clip.
![image](https://user-images.githubusercontent.com/14208261/194779469-1babb1aa-7897-434e-8283-c212af1226da.png)
![image](https://user-images.githubusercontent.com/14208261/194779472-1ea2c2c4-ca54-4643-8674-e582b7f84322.png)

j) Connect the pinion gear to the encoder and check that it rotates as smoothly as possible.
![image](https://user-images.githubusercontent.com/14208261/194779479-2ee558b1-ef91-4802-9216-6a4d6f4abf50.png)

k) Result after mounting the pinion gear and the encoder.
![image](https://user-images.githubusercontent.com/14208261/194779487-0e1a88ed-fcda-40e7-b195-ccf85b68f6f7.png)
![image](https://user-images.githubusercontent.com/14208261/194779490-08fb1014-5ab9-4658-8cd6-3cdfdf770a91.png)

*Tip1*: We use graphite lubricant mixed with lubricating oil to lubricate the transmission between the printed gears. 
Do not use too much to avoid the risk of falling into electrical components.

*Tip2*: After fitting the wheel, check by turning it so that the entire transmission runs as smoothly as possible. 
The wheel cannot be stuck. In this case, check the gear teeth and sand the imperfections. 
It may also be necessary to sand the base of the pinion gear so that it does not rub against the wheel.
This part is kind of boring, but it's crucial for the robot's control and odometry to work.


2) A way to couple the motor gear onto the servo shaft.

a) After modifying the servo motor for continuous rotation. Use the horn that comes with the servo kit to fit the motor gear.
![image](https://user-images.githubusercontent.com/14208261/194779550-d12ad091-5e94-4794-b70d-48a3fd076b4e.png)

b) Cut the horn leaving only the cylindrical connector.
![image](https://user-images.githubusercontent.com/14208261/194779556-d95b9234-16a9-4a67-9719-e74288b67def.png)

c) Trim the cylindrical connector evenly until it fits into the motor gear.
![image](https://user-images.githubusercontent.com/14208261/194779561-10e47c3c-609d-4b77-9242-3936ab191c2a.png)

d) Use super glue to prevent the connector from coming out of the motor gear.
![image](https://user-images.githubusercontent.com/14208261/194779567-afc705bd-7d0a-4332-90d8-0f75d8d61e4c.png)

e) Cut around 1.00-1.20mm from the motor shaft so that the motor gear is as close as possible.
Make it as flat as possible. Trim the shaft if necessary.
![image](https://user-images.githubusercontent.com/14208261/194779574-d473d349-1012-4802-bb0e-b984fdc6c29f.png)

f) Connect the gear motor to the motor shaft using the screw that comes with the servo kit.
![image](https://user-images.githubusercontent.com/14208261/194779579-ee7dd0af-b867-4ead-9b75-401b5c5f4f17.png)

g) Try connecting the servo to the board and let it work. 
![image](https://user-images.githubusercontent.com/14208261/194779584-7c6fd612-c63e-4e6f-87a3-b59eeed7f4e6.png)

h) The idea is to check/test that the gear motor fits well. 
It can't be too tight or too loose. It should also rotate as smoothly as possible so that the gear teeth pull the wheel correctly.
In this step, you can connect the wheel and see if the movement is fine.
![image](https://user-images.githubusercontent.com/14208261/194779589-06941ab0-b59d-470c-9646-b9fec3a73762.png)

Best,
Rezeck
