### ISSUE TITLE
Placing charging module

### ISSUE THREAD

**Issue by buddytex** [verlab/hero_common#32]
I'm unsure about the placement of the TP4056 charging module. The assembly materials include a SOP 8 version of the TP4056 so I'm unsure if the module is necessary. I noticed the marking 'B+' on the PCB, which suggests a connection point for the module. However, when I try to place the charging module, it seems awkward and out of place.
 I'm eagerly awaiting your guidance on where to position the module.

**Comment by rezeck** [comment]
Hi @buddytex,

Thank you for reaching out with your concern regarding the placement of the TP4056 charging module. Allow me to provide clarification on this matter.

In the current iteration of the board, specifically version 2.5 and later, we have integrated a TP4056 charging circuit directly onto the PCB. Consequently, the separate TP4056 module included in the assembly materials is no longer necessary. I understand your confusion regarding the 'B+' marking on the PCB, which indeed indicates the battery-positive connection point. However, this marking is intended for guiding the connection of the step-up (MT3608) module, rather than the TP4056.

![image](https://github.com/verlab/hero_common/assets/14208261/f340c1a7-415c-432e-b905-f289910f0753)

To offer further assistance, I've attached some images showcasing the board in its current version I have here (v2.5). You'll notice that in this version, a direct connection between the MT3608 and the board may require some wiring. However, in subsequent versions the alignment should be seamless, and you can utilize header pins for a secure connection.

![image](https://github.com/verlab/hero_common/assets/14208261/c43c219d-af9f-42dc-8494-6382a88663f4)

![image](https://github.com/verlab/hero_common/assets/14208261/31254c6e-843c-44ea-899e-92bc935b6d29)

![image](https://github.com/verlab/hero_common/assets/14208261/aeb38cc9-cc11-49be-bdd9-1e166b2ca135)

I hope this clears up any confusion, and please don't hesitate to ask if you need further assistance. We're here to help!

Best regards,
Rezeck
